import type { CameraManifest } from '../types';

const DATA_API_URL =
  import.meta.env.VITE_DATA_API_URL || 'https://data.dontgetflocked.com';

/** Filter dictionary — a few KB. Generated by the tile pipeline from the
 *  same snapshot as cameras-filter.pmtiles; the two must always match. */
export const CAMERA_MANIFEST_URL = `${DATA_API_URL}/cameras-manifest.json`;

let cached: CameraManifest | null = null;
let inFlight: Promise<CameraManifest> | null = null;

function assertManifestShape(data: unknown): asserts data is CameraManifest {
  const m = data as CameraManifest;
  if (
    !m ||
    !Array.isArray(m.brands) ||
    !Array.isArray(m.operators) ||
    !Array.isArray(m.zones) ||
    !Array.isArray(m.mounts)
  ) {
    throw new Error('Malformed camera manifest');
  }
}

export async function loadCameraManifest(): Promise<CameraManifest> {
  if (cached) return cached;
  if (inFlight) return inFlight;

  inFlight = (async () => {
    try {
      const res = await fetch(CAMERA_MANIFEST_URL);
      if (!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);
      const data: unknown = await res.json();
      assertManifestShape(data);
      cached = data;
      return data;
    } finally {
      inFlight = null;
    }
  })();
  return inFlight;
}

/** Test hook — not for app code. */
export function _resetManifestCacheForTests(): void {
  cached = null;
  inFlight = null;
}
