import type { CameraManifest } from '../types';
import {
  cameraFilterTileJsonUrl,
  cameraManifestUrl,
  type CameraTileCountry,
} from './cameraTilesService';

const cached = new Map<CameraTileCountry, CameraManifest>();
const inFlight = new Map<CameraTileCountry, Promise<CameraManifest>>();

function assertManifestShape(data: unknown): asserts data is CameraManifest {
  const m = data as CameraManifest;
  if (
    !m ||
    !Array.isArray(m.brands) ||
    !Array.isArray(m.operators) ||
    !Array.isArray(m.zones) ||
    !Array.isArray(m.mounts)
  ) {
    throw new Error('Malformed camera manifest');
  }
}

/** Cache-busting query param: the CDN keys on the full URL, so a unique
 *  param pulls the origin copy past any stale edge entry. */
const bust = (url: string) => `${url}${url.includes('?') ? '&' : '?'}fresh=${Date.now()}`;

/** Filter dictionary — a few KB per country. Generated by the tile pipeline
 *  from the same snapshot as that country's filter tileset; ids are
 *  build-scoped so the two are only valid as a matched pair.
 *
 *  `fresh: true` bypasses both the module cache and the CDN edge cache —
 *  used to recover when the cached manifest/tileset pair is skewed (edge
 *  entries for the two files can come from different hourly builds). */
export async function loadCameraManifest(
  country: CameraTileCountry = 'us',
  opts?: { fresh?: boolean }
): Promise<CameraManifest> {
  if (!opts?.fresh) {
    const hit = cached.get(country);
    if (hit) return hit;
    const pending = inFlight.get(country);
    if (pending) return pending;
  }

  const url = opts?.fresh ? bust(cameraManifestUrl(country)) : cameraManifestUrl(country);
  const promise = (async () => {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);
      const data: unknown = await res.json();
      assertManifestShape(data);
      cached.set(country, data);
      return data;
    } finally {
      inFlight.delete(country);
    }
  })();
  if (!opts?.fresh) inFlight.set(country, promise);
  return promise;
}

/**
 * Verifies the filter tileset and manifest came from the same pipeline build.
 * The pipeline stamps the manifest's `version` (16-hex hash of the source
 * snapshot) into the filter tileset's TileJSON `name`. Returns:
 *  - 'match'    — stamp found and equals the manifest version
 *  - 'mismatch' — stamp found and differs (stale pair; filtering would be wrong)
 *  - 'unknown'  — no stamp / fetch failed (older tileset build; skip the check)
 */
export async function verifyFilterTilesetVersion(
  manifestVersion: string,
  country: CameraTileCountry = 'us',
  opts?: { fresh?: boolean }
): Promise<'match' | 'mismatch' | 'unknown'> {
  try {
    const url = opts?.fresh
      ? bust(cameraFilterTileJsonUrl(country))
      : cameraFilterTileJsonUrl(country);
    const res = await fetch(url);
    if (!res.ok) return 'unknown';
    const tilejson: unknown = await res.json();
    const name = (tilejson as { name?: unknown }).name;
    if (typeof name !== 'string') return 'unknown';
    const stamp = name.match(/\b[0-9a-f]{16}\b/)?.[0];
    if (!stamp) return 'unknown';
    return stamp === manifestVersion ? 'match' : 'mismatch';
  } catch {
    return 'unknown';
  }
}

/** Test hook — not for app code. */
export function _resetManifestCacheForTests(): void {
  cached.clear();
  inFlight.clear();
}
