name = "flockhopper-data"
main = "src/index.ts"
compatibility_date = "2026-01-23"

routes = [
  { pattern = "data.dontgetflocked.com/*", zone_id = "8af99e9f48bbcacb0704614bcdcb0fec" }
]

[triggers]
crons = ["0 8 * * *"]

[limits]
cpu_ms = 30000

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "flockhopper-data"

[vars]
ENVIRONMENT = "production"
